# Generated by Django 3.1.6 on 2021-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
